### PR TITLE
Python 2 support returned

### PR DESCRIPTION
**Pull request by Vegasq**
- Just tried to deploy proj on one of mine raspberry, and discovered
  that there is a bug that do not allow me install django 1.7/1.8
  based on python 3 to raspbian. Everything worked with OOB py2.7
  and this little fix.
- If there some reason why we prefer to use Py3 nor Py2, please
  share it with me.

### CODE REVIEW

**Comment by Vegasq** [comment]
And you can share next link with guys who interested in proj, but lazy to install it localy:

http://pi.p3ka.com/

python 2.7
django 1.8
raspberry pi b+ / raspbian

**Comment by autogestion** [comment]
The reason is not to use an aging instrument

Why not deploy to aws with python 3 support?
There could be much more adventures on raspbian with this project, not only Py3 problem

Also, there could be a branch specail for deploy on your raspberry

**Comment by autogestion** [comment]
Also, there could be a branch specail for deploy on your raspberry

**Comment by Dovbo** [comment]
WindowsPhone8. Error when I tried to sign up with e-mail field not empty. With empty e-mail field ok. Can't add anon claim. With registered user seems like button doesn't works.

**Comment by Vegasq** [comment]
> Why not deploy to aws with python 3 support?
> Vendor lock it is not really good idea. Especially if only problem is
> argument to function.
> 
> Also, there could be a branch specail for deploy on your raspberry
> Well... What is the goal?
> 
> WindowsPhone8. Error when I tried to sign up with e-mail field not empty.
> With empty e-mail field ok. Can't add anon claim. With registered user
> seems like button doesn't works.

Oh. Thx u for such report :)
Yes, I see error during account creation. It require configured mail server
on host system (to send confirm mail). Will fix it later today.
But as for anon claim and not working button - looks OK from my Android.
Will check with latest IE. I hope they have same engine inside.

**Comment by Vegasq** [comment]
> Will check with latest IE

Just checked with IE11. No problems were found. Please attach more information about problem. But due to changes in this patchset - problem looks not to be related here, so we need new issue for it.

**Pull request merged**
