### PR TITLE
Visual improvements

### PR DESCRIPTION
**Pull request by Vegasq**
Was:

Become:

- stolen from police.kh.ua map overview

### CODE REVIEW

**Comment by Vegasq** [comment]
Screenshots a bit out-of-date. Please check on your own.

**Comment by autogestion** [comment]
How this would looks like, if there would be 100 claims returned by get claims?

**Comment by Vegasq** [comment]
Block will be 100% of window height and became scrollable inside.

**Comment by Vegasq** [comment]
Small bug fixed. Previously we've lost last 52px of claims.

**Pull request closed without merging**
